package com.example.TallyNewErp.mapper;

import com.example.TallyNewErp.dto.NewLedgerCreateDto;
import com.example.TallyNewErp.model.NewLedgerCreate;

public class NewLedgerCreateMapper {


//    this both functions works as dto for client and server


    public static NewLedgerCreateDto mapToNewLedgerCreateDto(NewLedgerCreate newledgercreate){
        return new NewLedgerCreateDto(
                newledgercreate.getLedgerName(),
                newledgercreate.getTallySerialNo(),
                newledgercreate.getAliasName(),
                newledgercreate.getUnderGroup(),
                newledgercreate.getSubUnder(),
                newledgercreate.getTypeOfLedger(),
                newledgercreate.getMaintainBalancesBillByBill(),
                newledgercreate.getDefaultCreditPeriod(),
                newledgercreate.getCheckForCreditDaysDuringVoucherEntry(),
                newledgercreate.getTypeOfDutyOrTax(),
                newledgercreate.getCostsCentresAreApplicable(),
                newledgercreate.getPercentageOfCalculation(),
                newledgercreate.getOdLimit(),
                newledgercreate.getIncludeInAssessableValueCalculation(),
                newledgercreate.getGstApplicability(),
                newledgercreate.getHsnOrSacAndRelatedDetails(),
                newledgercreate.getSourceOfDetails(),
                newledgercreate.getHsnOrSac(),
                newledgercreate.getHsnOrSacDescription(),
                newledgercreate.getClassification(),
                newledgercreate.getGstRateDetails(),
                newledgercreate.getTaxabilityType(),
                newledgercreate.getNatureOfTransaction(),
                newledgercreate.getIgstRate(),
                newledgercreate.getCgstRate(),
                newledgercreate.getUtgstRate(),
                newledgercreate.getTypeOfSupply(),
                newledgercreate.getAccountHoldersName(),
                newledgercreate.getAccountNumber(),
                newledgercreate.getIfscCode(),
                newledgercreate.getSwiftCode(),
                newledgercreate.getBankName(),
                newledgercreate.getBranchName(),
                newledgercreate.getAlterRangeForChequeBooks(),
                newledgercreate.getEnableChequePrinting(),
                newledgercreate.getAlterChequePrintingConfiguration(),
                newledgercreate.getContactPerson(),
                newledgercreate.getContactPhoneNumber(),
                newledgercreate.getMobileNumber(),
                newledgercreate.getEmail(),
                newledgercreate.getMailingName(),
                newledgercreate.getAddressOne(),
                newledgercreate.getAddressTwo(),
                newledgercreate.getAddressThree(),
                newledgercreate.getAddressFour(),
                newledgercreate.getAddressFive(),
                newledgercreate.getStateName(),
                newledgercreate.getCountryName(),
                newledgercreate.getPinCode(),
                newledgercreate.getProvideBankDetails(),
                newledgercreate.getPanOrItNumber(),
                newledgercreate.getRegistrationType(),
                newledgercreate.getGstOrUin(),
                newledgercreate.getSetOrAlterGstDetails(),
                newledgercreate.getOpeningBalance()
        );
    }


    public static NewLedgerCreate mapToNewLedgerCreate(NewLedgerCreateDto newledgercreatedto){

        return new NewLedgerCreate(
                newledgercreatedto.getLedgerName(),
                newledgercreatedto.getTallySerialNo(),
                newledgercreatedto.getAliasName(),
                newledgercreatedto.getUnderGroup(),
                newledgercreatedto.getSubUnder(),
                newledgercreatedto.getTypeOfLedger(),
                newledgercreatedto.getMaintainBalancesBillByBill(),
                newledgercreatedto.getDefaultCreditPeriod(),
                newledgercreatedto.getCheckForCreditDaysDuringVoucherEntry(),
                newledgercreatedto.getTypeOfDutyOrTax(),
                newledgercreatedto.getCostsCentresAreApplicable(),
                newledgercreatedto.getPercentageOfCalculation(),
                newledgercreatedto.getOdLimit(),
                newledgercreatedto.getIncludeInAssessableValueCalculation(),
                newledgercreatedto.getGstApplicability(),
                newledgercreatedto.getHsnOrSacAndRelatedDetails(),
                newledgercreatedto.getSourceOfDetails(),
                newledgercreatedto.getHsnOrSac(),
                newledgercreatedto.getHsnOrSacDescription(),
                newledgercreatedto.getClassification(),
                newledgercreatedto.getGstRateDetails(),
                newledgercreatedto.getTaxabilityType(),
                newledgercreatedto.getNatureOfTransaction(),
                newledgercreatedto.getIgstRate(),
                newledgercreatedto.getCgstRate(),
                newledgercreatedto.getUtgstRate(),
                newledgercreatedto.getTypeOfSupply(),
                newledgercreatedto.getAccountHoldersName(),
                newledgercreatedto.getAccountNumber(),
                newledgercreatedto.getIfscCode(),
                newledgercreatedto.getSwiftCode(),
                newledgercreatedto.getBankName(),
                newledgercreatedto.getBranchName(),
                newledgercreatedto.getAlterRangeForChequeBooks(),
                newledgercreatedto.getEnableChequePrinting(),
                newledgercreatedto.getAlterChequePrintingConfiguration(),
                newledgercreatedto.getContactPerson(),
                newledgercreatedto.getContactPhoneNumber(),
                newledgercreatedto.getMobileNumber(),
                newledgercreatedto.getEmail(),
                newledgercreatedto.getMailingName(),
                newledgercreatedto.getAddressOne(),
                newledgercreatedto.getAddressTwo(),
                newledgercreatedto.getAddressThree(),
                newledgercreatedto.getAddressFour(),
                newledgercreatedto.getAddressFive(),
                newledgercreatedto.getStateName(),
                newledgercreatedto.getCountryName(),
                newledgercreatedto.getPinCode(),
                newledgercreatedto.getProvideBankDetails(),
                newledgercreatedto.getPanOrItNumber(),
                newledgercreatedto.getRegistrationType(),
                newledgercreatedto.getGstOrUin(),
                newledgercreatedto.getSetOrAlterGstDetails(),
                newledgercreatedto.getOpeningBalance()
        );
    }
}
